### ISSUE TITLE
It seems to be a typo in the code

### ISSUE THREAD

**Issue by dakyskye** [jonas747/yagpdb#748]
[line 37](https://github.com/jonas747/yagpdb/blob/master/bot/bot.go#L37) it seems to be a typo:
> config.RegisterOption("yagpdb.connevt.channel", "Gateway connection logging channel", 0)

> yagpdb.connevt.channel

> **connevt**

**Comment by Jo3-L** [comment]
Perhaps Jonas meant `connevt` to be short for "connection event" rather than `connect`? Not sure though.

**Comment by dakyskye** [comment]
Possible, I am not sure either.

**Comment by RedFlames** [comment]
Since I've randomly clicked on this issue and was curious about the typo:

```
# Send discord gateway connection events to a discord channel
YAGPDB_CONNEVT_CHANNEL=""
```
Found this in [sampleenvfile l. 59/60](https://github.com/jonas747/yagpdb/blob/c4574009722d26d1adc1dab52808b344917b1945/cmd/yagpdb/sampleenvfile#L59) (it also shows up in the docker sample env)

Oh and there's also
`	connEvtChannel := confConnEventChannel.GetInt()` in [bot.go l.383](https://github.com/jonas747/yagpdb/blob/60a4149846515aa15642a0974deff45d8b9d08ae/bot/bot.go#L383) which has **connEvt** in camel case.

So that seems to back up Joe's theory. :thinking:

**Comment by mrbentarikau** [comment]
really don't understand why this is still open?
"connevt", connection event.... where's the typo

also, why chase typos in working code?

**Comment by dakyskye** [comment]
I’m sorry, just found out this issue is open. Yeah, my bad for getting field name wrong.
