### ISSUE TITLE
Automoderator V2 Delete welcome Messages?

### ISSUE THREAD

**Issue by B-iggy** [jonas747/yagpdb#967]
Hi Jonas,
great project!

With the recent mess going on with this black hat raider (https://www.reddit.com/r/discordapp/comments/nuz8jj/so_h0nde_has_made_an_account_using_your_email/) 
I discovered your Discord bot and the regex function to clean new member accounts or based on this username (h0nde).
And this is working great.
However, I have a channel that greets my new people. That greeting message is generated by a bot and the Automoderator V2 Effect Type "Delete Message" does not work for such generated messages. (?)

Is there a way to clean the welcome message from such bot/raid fools?

Ideally the welcome message from YAGPDB itself has a toggle or way to show it only to not blacklisted users.

**Comment by Wolveric** [comment]
YAGPDB doesn't register them, because bots shouldn't respond to bots, ***especially*** not themselves.

Otherwise, as YAGPDB's welcome message is a Template Field, I added a RegEx check on username to a welcome message on a server I administrate, that will only run the rest of message, if the user's name does not match the given pattern.

In the case you're not embedding your welcome message, and you'd like up clean up current ones though, you could use the built-in `-clean` command to clear messages in bulk.

**Comment by B-iggy** [comment]
thanks for your response! I assumed the bot war already ;)

May I ask where / how you set your Template Field? I just installed YAGPDB today.
Your solution sounds perfect.

My welcome message was from carl.gg. Half text, half embedded. But can change it then.

**Comment by Wolveric** [comment]
It uses Go's Text Template scripting library, for which you can find a learning course [here](https://learn.yagpdb.xyz/) for technical aspects.

Otherwise, generally you should join YAGPDB's [support server](https://discord.gg/4udtcA5), rather than using GitHub, for further enquiries.

**Comment by B-iggy** [comment]
Thanks @Wolveric 
the documentation is really great here and I was able to achieve everything I wanted.
For anyone interested:
To not show welcome messages to "bots" aka raider, etc.
```
{{if gt (currentUserAgeMinutes) 1}}
>> Your welcome text to legit user <<
{{end}}
```
